### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by drorberel** [RamiKrispin/sfo#1]
> devtools::install_github("RamiKrispin/sfo") Error: Failed to install 'unknown package' from GitHub:   HTTP error 404.   No commit found for the ref master    Did you spell the repo owner (`RamiKrispin`) and repo name (`sfo`) correctly?   - If spelling is correct, check that you have the required permissions to access the repo.
--
 
> | >
>

**Comment by RamiKrispin** [comment]
Thanks, this is related to the recent change in Github branches default name, which was changed from `master` to `main`. I will update the readme. This should work:
`devtools::install_github("RamiKrispin/sfo", ref = "main")`

**Comment by RamiKrispin** [comment]
I see that in the most recent version the default `ref` value was set to `HEAD`
