### ISSUE TITLE
sort the nodes within each cat_cols in sankey plot by sankey_ly

### ISSUE THREAD

**Issue by zhengyonglan** [RamiKrispin/sfo#4]
Hi, 
sankey_ly looks terrific! Is it possible to sort the nodes within each cat_cols? Thanks!

**Comment by RamiKrispin** [comment]
Hi @zhengyonglan sorry for the late response, I will check how simple it is to make this modification.

**Comment by RamiKrispin** [comment]
Hi @zhengyonglan, working on the next release, I was trying to add the functionality you ask, unfortunately, there is no simple way to create it due to the complexity of the nodes' mapping.
